blank_issues_enabled: true
contact_links:
  - name: Security Vulnerability
    about: Please report security vulnerabilities to hello@openfresno.org.
  - name: Open Fresno Documentation
    about: Learn more about Open Fresno and how to contribute.
    url: https://openfresno.github.io/fe-openfresno.org-doc
